# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.12' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  GO111MODULE: 'on' # enable Go modules
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- task: GoTool@0
  inputs:
    version: '1.12'

- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable

- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'

- script: |
    go version
    go mod vendor
    go get -u golang.org/x/lint/golint
    go build -v .
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies'

- script: |
    go build -v
    go fmt ./...
    golint $(go list ./... | grep -v /vendor/)
    go vet ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Build and run static analysis'

- script: |
    docker-compose -f dev/docker-compose.yml up -d
    docker ps
    # go test -coverprofile=coverage.txt -covermode=atomic -race -short ./...
    go test -coverprofile=coverage.txt -covermode=atomic -short ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Set up devenv and run tests'

- script: bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN)
  workingDirectory: '$(modulePath)'
  displayName: 'Report coverage'
  condition: succeeded()
