version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5431:5432"
    volumes:
      - ./db/sql:/sql
    environment:
      POSTGRES_DB: "projector-dev"
      POSTGRES_USER: "bobheadxi"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
