package analysis

import (
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"go.uber.org/zap/zaptest"

	"github.com/bobheadxi/timelines/git"
)

func TestGitRepoAnalyser(t *testing.T) {
	// get repo
	l := zaptest.NewLogger(t).Sugar()
	m := git.NewManager(l.Named("git-manager"), git.ManagerOpts{Workdir: "./tmp"})
	repo, err := m.Download(
		context.Background(),
		"https://github.com/bobheadxi/calories.git",
		git.DownloadOpts{})
	assert.NoError(t, err)
	defer os.RemoveAll("./tmp")

	// execute analysis
	a, err := NewGitAnalyser(l.Named("analysis"), repo.GitRepo(), GitRepoAnalyserOptions{})
	assert.NoError(t, err)
	report, err := a.Analyze()
	assert.NoError(t, err)

	// print meta
	b, _ := json.MarshalIndent(report.Meta, "", "  ")
	os.Remove("test.meta.json")
	ioutil.WriteFile("test.meta.json", b, os.ModePerm)

	// print burndown
	b, _ = json.MarshalIndent(report.Burndown, "", "  ")
	os.Remove("test.burndown.json")
	ioutil.WriteFile("test.burndown.json", b, os.ModePerm)

	// print coupling
	b, _ = json.MarshalIndent(report.Coupling, "", "  ")
	os.Remove("test.coupling.json")
	ioutil.WriteFile("test.coupling.json", b, os.ModePerm)

	// generate test data
	ioutil.WriteFile("testdata/git.go", []byte(fmt.Sprintf(`
// Code generated by github.com/bobheadxi/timelines/analysis/integration_test.go, DO NOT EDIT.
package testdata

import (
	"github.com/bobheadxi/timelines/analysis"
)

// Burndown is an example output from a git repo analysis
// The data is sourced from the analysis done in analysis/integration_test.go
var (
	Burndown = %#v
	Coupling = %#v
)
`, report.Burndown, report.Coupling)), os.ModePerm)
}
